@extends('layouts.app')
@section('title')
Privacy Policy
@endsection
@section('content')
<section class="banner inner-payment" style="background-image: url({{url('/')}}/images/hero-home.png);">
    <div class="container">
        <div class="col-sm-12">
            <div class="row align-items-center justify-content-center pt-5">
                <div class="card-body">
                    <h1>Privacy PLolicy</h1>
                </div>
            </div>
        </div>
    </div>
</section>
<section class="deals">
    <div class="container">
        <div class="row">
            <div><strong>General Terms of VisaBadge,</strong></div>
            <div>
                <ol>
                    <li>Our privacy policy abide by the Information &amp; Technology Act, 2000, 2008 &amp; 2011, in accordance with Rule 3-1 (intermediaries guidelines) requiring rules &amp; regulations, privacy policy &amp; T&amp;C for the usage of&nbsp;<a href="http://visabadge.com/" target="_blank">visabadge.com</a>&nbsp;and its associated properties</li>
                    <li>This is an electronic document, which doesn't need a physical signature</li>
                    <li>Usage of its properties is solely governed by the T&amp;C captured here as well as the privacy policy&nbsp;</li>
                    <li>Visit to any of its properties shall be deemed to signify the user's unequivocal acceptance of its privacy policy</li>
                    <li>User agreed that the&nbsp;privacy policy&nbsp;mentioned constitute a legally binding agreement between user and VisaBadge</li>
                    <li>VisaBadge reserves exclusive right to amend or modify the policies anytime, without the permission from user</li>
                    <li><strong>Collection &amp; use of personal &amp; other information,</strong></li>
                    <ol>
                        <li>The User expressly agrees and acknowledges that the Company collects and stores the User&rsquo;s personal information, which is provided by the User from time to time on the Website, including but not limited to the User&rsquo;s Name, date of birth, sex, address, user name, passwords, email address, shopping preferences, browsing history, etc., as well as any images or other information uploaded/published by the User on the Website. The User is aware that this information will be used by the Company/Website to provide services and features targeted at the User, that are most likely to meet the User&rsquo;s needs, and also to customize and improve the Website to make its users&rsquo; experiences safer and easier.</li>
                        <li>The User is aware that the Company/Website may automatically track certain information about the User based upon the User&rsquo;s IP address and the User&rsquo;s behaviour on the Website, and the User expressly consents to the same. The User is aware that this information is used to do internal research on user demographics, interests, and behaviour, to enable the Company/Website to better understand, and cater to the interests of its users. The User is expressly made aware that such information may include the URL that the User visited prior to accessing the Website, the&nbsp;URL which the User subsequently visits (whether or not these URLs form a part of the Website), the User&rsquo;s computer &amp; web browser information, the User&rsquo;s IP address, etc</li>
                        <li>If the User chooses to purchase services from the Website, the User consents to allowing the Company/Website to collect information about the User&rsquo;s buying behaviour and trends.</li>
                        <li>If the User chooses to post messages/reviews/feedback anywhere on the Website, including but not limited to message boards, chat rooms, other message areas, etc., the User is aware that any and all such information provided/uploaded will be collected and stored by the Company indefinitely, and that such retained information may be used to resolve disputes, provide customer support, troubleshoot problems, etc., and that such information, if requested, may be provided to judicial or governmental authorities of requisite jurisdiction, or otherwise used by the Company/Website as permitted by applicable laws.</li>
                        <li>The User is aware that any and all information pertaining to the User collected by the Company, whether or not directly provided by the User to the Company/Website, including but not limited to personal correspondence such as emails or letters, feedback from other users or third parties regarding the User&rsquo;s activities or postings on the Website, etc, may be collected and compiled by the Company/Website into a file/folder specifically created for/allotted to the User, and the User hereby expressly consents to the same.</li>
                        <li>The User is aware that while he/she can browse some sections of the Website without being a registered user, certain activities require the User to provide valid personal information to the Company/Website for the purpose of registration. The User is aware that the contact information provided to the Company/Website may be used to send the User offers and promotions, whether or not based on the User&rsquo;s previous orders and&nbsp;interests, and the User hereby expressly consents to receiving the same.</li>
                        <li>The User is aware that the Company/Website may occasionally request the User to complete optional online surveys. These surveys may require the User to provide contact information and demographic information (like zip code, age, income bracket, sex, etc.). The User is aware that this data too is used to customise the Website for the benefit of the User, and providing all users of the Website with products/services/content that the Company/Website believes they might be interested in availing of, and also to display content according to the User&rsquo;s preferences.</li>
                        <li>The User is further aware that the Company/Website may occasionally request the User to write reviews for products/services purchased/availed of by the User from the Website. The User is aware that such reviews will help other users of the Website make prudent and correct purchases and the User hereby expressly authorises the Company/Website to publish any and all reviews written by the User on the Website, along with the User&rsquo;s name and certain contact details, for the benefit and use of other Users of the Website.</li>
                        <li>Nothing contained herein shall be deemed to compel the Website /Company to store, upload, publish, or display in any manner content/reviews/surveys/<wbr />feedback submitted by the User, and the User hereby expressly authorises the Website/Company to remove from the Website any such content, review, survey, or feedback submitted by the User, without cause or being required to notify the User of the same.</li>
                    </ol>
                    <li><strong>Usage of Cookies:</strong>&nbsp;The User is aware that a &lsquo;Cookie&rsquo; is a small piece of information stored by a web server on a web browser so it can later be traced back from that particular&nbsp;browser, and that cookies are useful for enabling the browser to remember information specific to a given user, including but not limited to&nbsp;a User&rsquo;s login identification, password, etc. The User is aware that the Website places both permanent and temporary cookies in the User&rsquo;s computer's hard drive &amp; Mobile Phone&rsquo;s Memory Storage unit and web browser, and does hereby expressly consent to the same.&nbsp;The User is further aware that the Website uses data collection devices such as cookies on certain pages of the Website to help analyse web page flow, measure promotional effectiveness, and promote trust and safety, and that certain features of the Website are only available through the use of such cookies. While the User is free to decline the Website cookies if the User&rsquo;s browser permits, the User may consequently be unable to use certain features on the Website.&nbsp;Additionally, the User is aware that he/she might encounter &lsquo;cookies&rsquo; or other similar devices on certain pages of the Website that are placed by third parties or affiliates of the Company/Website. The User expressly agrees and acknowledges that the Company/Website does not control the use of such cookies/other devices by third parties, that the Company/Website is in no way responsible for the same, and that the User assumes any and all risks in this regard.</li>
                    <li><strong>Sharing of personal information:</strong>&nbsp;The User is aware that the Website/Company may share the User&rsquo;s personal information with other corporate entities and affiliates to help detect and prevent identity theft, fraud and other potentially illegal acts; correlate related or multiple accounts to prevent abuse of the Website services; and to facilitate joint or co-branded services, where such services are provided by more than one corporate entity.&nbsp;The User is aware that the Website/Company may disclose personal information if required to do so by law or if the Website/Company in good&nbsp;faith believes that such disclosure is reasonably necessary to respond to subpoenas, court orders, or other legal processes. The Website/Company may also disclose the User&rsquo;s personal information to law enforcement offices, third party rights owners, or other third parties if it believes that such disclosure is reasonably necessary to enforce the Terms or Policy; respond to claims that an advertisement, posting or other content violates the rights of a third party; or protect the rights, property or personal safety of its users, or the general public.&nbsp;The User is further aware that the Website/Company and its affiliates may share / sell some or all of the User&rsquo;s personal information with other business entities should the Company/Website (or its assets) plan to merge with, or be acquired by such business entity, or in the event of&nbsp;re-organization, amalgamation, or restructuring of the Company&rsquo;s business. Such business entity or new entity will continue to be bound by the Terms and Policy, as may be amended from time to time.&nbsp;The User is further aware that the Website/Company will share the user&rsquo;s personal information with payment&nbsp;gateway&nbsp;in order to process the payments in a swift manner.</li>
                    <li><strong>Security:</strong>&nbsp;Transactions on the Website are secure and protected. Any information entered by the User when transacting on the Website is encrypted to protect the User against unintentional disclosure to third parties. The User&rsquo;s credit and debit card information maybe received, stored by or retained by the Company/Website for the purpose of providing a &ldquo;Quick Checkout&rdquo; facility to the User. This information is supplied by the User directly to the relevant payment gateway which is authorized to handle the information provided, and is compliant with the regulations and requirements of various banks and institutions and payment franchisees that it is associated with.&nbsp;</li>
                    <li><strong>User Consent:&nbsp;</strong>By using the Website and/ or by providing information to the Company through the Website, the User consents to the collection and use of the information disclosed by the User on the Website in accordance with this Policy, including but not limited to the User&rsquo;s consent the Company/Website/sharing/<wbr />divulging the User&rsquo;s information, as per the terms contained hereinabove in Section 4 of the Policy.</li>
                    <li><strong>Dispute Resolution:</strong>&nbsp;The Parties expressly agree that the Terms, Policy and any other agreements entered into between the Parties are governed by the laws, rules and regulations of India, and that the Courts at Kochi, Kerala shall have exclusive jurisdiction over any disputes arising between the Parties</li>
                </ol>
            </div>
        </div>
    </div>
</section>
@endsection